baseurl = "http://spencer.gibb.us"
languageCode = "en-us"
title = "Spencer Gibb"
builddrafts = true
copyright = "Copyright (c) 2013 - 2015, Spencer Gibb; all rights reserved."
canonifyurls = true
# theme = "hyde-x-custom"
theme = "beautifulhugo"

[author]
    name = "Spencer Gibb"
    github = "spencergibb"
    linkedin = "spencergibb"
    stackoverflow = "2730527/spencergibb"
    twitter = "spencerbgibb"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

[indexes]
    # Optional. Use if you want tags and lists.
    category = "categories"

[Params]
    logo = "images/spencer-gibb-square-med.jpg"
    subtitle = "tech musings"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Presentations"
    url = "/categories/presentations/"
    weight = 2
